#!/usr/bin/env python3
"""Back up the irreplaceable measurement archives to GitHub WITHOUT the git CLI.

WHY THIS EXISTS. Under launchd, git dies at startup: getcwd() is TCC-denied for a
repo under ~/Desktop, so `git push` never runs (verified 8/22-8/23, both the
--git-dir form and `git -C`: "GIT PUSH FAILED both ways ... THE TAPE IS NOT BACKED
UP"). Python does not call getcwd() for HTTP, and it reads the archives via
relative paths from cwd=$PROJ exactly as sweep.py and build.py already do, so it
works where git cannot. This commits the append-only archives on top of the
current remote main via the GitHub Git Data API, uploading only blobs whose
content actually changed. Run from the repo root:  python3 tools_push_backup.py

WHAT IT BACKS UP. Only the datasets that cannot be recomputed if lost: the
settlement tape (data/history), the probe and schema archives (data/probe,
data/schemas), and the raw paid-call captures (captures). Everything else in the
repo is regenerated by the pipeline and is pushed whenever an interactive session
commits, so it is not this job's responsibility.

TOKEN. Reads $GITHUB_TOKEN / $GH_TOKEN, else ~/.config/whatagentsbuy/github_token
(chmod 600). Needs `repo` scope. If it is missing or rejected the script exits
non-zero so the daily job's fail() emails, rather than failing silently.
"""
import base64, hashlib, json, os, time, urllib.request, urllib.error

REPO = "neilkpatel/touchstone"
BRANCH = "main"
# The append-only, cannot-recompute datasets (see .gitignore, which tracks these
# deliberately). A missed day of the tape is gone forever; a raw capture cannot be
# re-fetched. These must not live only on one laptop.
BACKUP_DIRS = ["data/history", "data/probe", "data/schemas", "captures"]
EXCLUDE_SUFFIX = (".pyc", ".pem")
EXCLUDE_NAME = {".DS_Store"}
API = "https://api.github.com"


def _token():
    for env in ("GITHUB_TOKEN", "GH_TOKEN"):
        if os.environ.get(env):
            return os.environ[env].strip()
    p = os.path.expanduser("~/.config/whatagentsbuy/github_token")
    if os.path.exists(p):
        return open(p).read().strip()
    raise SystemExit("no GitHub token (set GITHUB_TOKEN or ~/.config/whatagentsbuy/github_token)")


TOKEN = _token()


def api(path, method="GET", body=None):
    url = path if path.startswith("http") else API + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method, headers={
        "Authorization": f"Bearer {TOKEN}",
        "Accept": "application/vnd.github+json",
        "User-Agent": "whatagentsbuy-backup/1.0",
        "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def git_blob_sha(data: bytes) -> str:
    """The SHA-1 git assigns a blob, so we can compare to the remote tree and skip
    files that are byte-identical to what is already pushed."""
    h = hashlib.sha1()
    h.update(b"blob %d\0" % len(data))
    h.update(data)
    return h.hexdigest()


def local_files():
    out = {}
    for d in BACKUP_DIRS:
        if not os.path.isdir(d):
            continue
        for root, _, files in os.walk(d):
            for fn in files:
                if fn in EXCLUDE_NAME or fn.endswith(EXCLUDE_SUFFIX):
                    continue
                p = os.path.join(root, fn)
                with open(p, "rb") as fh:
                    out[p] = fh.read()
    return out


def main():
    files = local_files()
    if not files:
        raise SystemExit("no archive files found; run from the repo root")

    # Try up to twice: if an interactive push lands the ref between our read and
    # our write, re-read head+tree and rebuild on the new base.
    for attempt in (1, 2):
        ref = api(f"/repos/{REPO}/git/ref/heads/{BRANCH}")
        head = ref["object"]["sha"]
        base_tree = api(f"/repos/{REPO}/git/commits/{head}")["tree"]["sha"]
        remote = api(f"/repos/{REPO}/git/trees/{base_tree}?recursive=1")
        remote_sha = {e["path"]: e["sha"] for e in remote.get("tree", []) if e["type"] == "blob"}

        changed = [(p, d) for p, d in files.items() if remote_sha.get(p) != git_blob_sha(d)]
        if not changed:
            print(f"backup: nothing changed across {len(files)} archived files; current at {head[:10]}")
            return

        tree = []
        for p, d in changed:
            blob = api(f"/repos/{REPO}/git/blobs", "POST",
                       {"content": base64.b64encode(d).decode(), "encoding": "base64"})
            tree.append({"path": p, "mode": "100644", "type": "blob", "sha": blob["sha"]})
        new_tree = api(f"/repos/{REPO}/git/trees", "POST", {"base_tree": base_tree, "tree": tree})
        msg = f"Daily backup: settlement tape + archives {time.strftime('%Y-%m-%d')} ({len(changed)} files)"
        commit = api(f"/repos/{REPO}/git/commits", "POST",
                     {"message": msg, "tree": new_tree["sha"], "parents": [head]})
        try:
            api(f"/repos/{REPO}/git/refs/heads/{BRANCH}", "PATCH", {"sha": commit["sha"], "force": False})
        except urllib.error.HTTPError as e:
            if e.code in (409, 422) and attempt == 1:
                print("backup: ref moved under us, retrying on the new head")
                continue
            raise
        print(f"backup: pushed {len(changed)} changed file(s) as {commit['sha'][:10]}")
        return


if __name__ == "__main__":
    main()
